name: uix_standalone
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
dependencies:
  collection: any
  source_gen: any
dev_dependencies:
  unittest: any
  shelf: any
